/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DoorId = IDL.Nat;
export const AttachmentId = IDL.Nat;
export const Time = IDL.Int;
export const LeafConfig = IDL.Variant({
  'doubleLeaf' : IDL.Null,
  'astragalBar' : IDL.Null,
  'singleLeaf' : IDL.Null,
});
export const DoorType = IDL.Variant({
  'double' : IDL.Null,
  'hinged' : IDL.Null,
  'sliding' : IDL.Null,
  'single' : IDL.Null,
});
export const DoorMaterial = IDL.Variant({
  'timber' : IDL.Null,
  'aluminium' : IDL.Null,
  'hybrid' : IDL.Null,
  'steel' : IDL.Null,
});
export const FrameMaterial = IDL.Variant({
  'metal' : IDL.Null,
  'timber' : IDL.Null,
  'uPVC' : IDL.Null,
  'hybrid' : IDL.Null,
});
export const FireRating = IDL.Variant({
  'sixtyMinutes' : IDL.Null,
  'thirtyMinutes' : IDL.Null,
  'oneHundredTwentyMinutes' : IDL.Null,
  'ninetyMinutes' : IDL.Null,
});
export const Door = IDL.Record({
  'id' : DoorId,
  'floor' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : Time,
  'building' : IDL.Text,
  'company' : IDL.Text,
  'dimensions' : IDL.Text,
  'leafConfig' : LeafConfig,
  'doorType' : DoorType,
  'notes' : IDL.Text,
  'doorMaterial' : DoorMaterial,
  'frameMaterial' : FrameMaterial,
  'location' : IDL.Text,
  'fireRating' : FireRating,
});
export const InspectionId = IDL.Nat;
export const Checklist = IDL.Record({
  'frame' : IDL.Bool,
  'glazing' : IDL.Bool,
  'certificatePlate' : IDL.Bool,
  'doorCloser' : IDL.Bool,
  'threshold' : IDL.Bool,
  'signage' : IDL.Bool,
  'hinges' : IDL.Bool,
  'latch' : IDL.Bool,
  'seals' : IDL.Bool,
  'intumescentStrip' : IDL.Bool,
  'doorLeaf' : IDL.Bool,
  'noObstructions' : IDL.Bool,
  'selfClosing' : IDL.Bool,
  'visionPanel' : IDL.Bool,
});
export const InspectionStatus = IDL.Variant({
  'fail' : IDL.Null,
  'pass' : IDL.Null,
  'actionRequired' : IDL.Null,
});
export const Inspection = IDL.Record({
  'id' : InspectionId,
  'inspectionDate' : Time,
  'doorId' : DoorId,
  'inspectorName' : IDL.Text,
  'createdAt' : Time,
  'company' : IDL.Text,
  'notes' : IDL.Text,
  'checklist' : Checklist,
  'overallStatus' : InspectionStatus,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'pending' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'principal' : IDL.Principal,
  'status' : ApprovalStatus,
});
export const DoorAttachment = IDL.Record({
  'id' : AttachmentId,
  'doorId' : DoorId,
  'filename' : IDL.Text,
  'blobHash' : IDL.Text,
  'uploadedAt' : Time,
});
export const StripeConfiguration = IDL.Record({
  'secretKey' : IDL.Text,
  'allowedCountries' : IDL.Vec(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'currency' : IDL.Text,
  'productName' : IDL.Text,
  'productDescription' : IDL.Text,
  'priceInCents' : IDL.Nat,
  'quantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDoor' : IDL.Func([Door], [DoorId], []),
  'addInspection' : IDL.Func([Inspection], [InspectionId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'deleteDoor' : IDL.Func([DoorId], [], []),
  'editDoor' : IDL.Func([DoorId, Door], [], []),
  'getAllDoors' : IDL.Func([], [IDL.Vec(Door)], ['query']),
  'getAllInspections' : IDL.Func([], [IDL.Vec(Inspection)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoor' : IDL.Func([DoorId], [Door], ['query']),
  'getDoorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getInspection' : IDL.Func([InspectionId], [Inspection], ['query']),
  'getInspectionsForDoor' : IDL.Func([DoorId], [IDL.Vec(Inspection)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getPublicDoor' : IDL.Func([DoorId], [IDL.Opt(Door)], ['query']),
  'getPublicInspectionsForDoor' : IDL.Func([DoorId], [IDL.Vec(Inspection)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'createCheckoutSession' : IDL.Func([IDL.Vec(ShoppingItem), IDL.Text, IDL.Text], [IDL.Text], []),
  'addDoorAttachment' : IDL.Func([DoorId, IDL.Text, IDL.Text], [AttachmentId], []),
  'getDoorAttachments' : IDL.Func([DoorId], [IDL.Vec(DoorAttachment)], ['query']),
  'removeDoorAttachment' : IDL.Func([DoorId, AttachmentId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DoorId = IDL.Nat;
  const AttachmentId = IDL.Nat;
  const Time = IDL.Int;
  const LeafConfig = IDL.Variant({
    'doubleLeaf' : IDL.Null,
    'astragalBar' : IDL.Null,
    'singleLeaf' : IDL.Null,
  });
  const DoorType = IDL.Variant({
    'double' : IDL.Null,
    'hinged' : IDL.Null,
    'sliding' : IDL.Null,
    'single' : IDL.Null,
  });
  const DoorMaterial = IDL.Variant({
    'timber' : IDL.Null,
    'aluminium' : IDL.Null,
    'hybrid' : IDL.Null,
    'steel' : IDL.Null,
  });
  const FrameMaterial = IDL.Variant({
    'metal' : IDL.Null,
    'timber' : IDL.Null,
    'uPVC' : IDL.Null,
    'hybrid' : IDL.Null,
  });
  const FireRating = IDL.Variant({
    'sixtyMinutes' : IDL.Null,
    'thirtyMinutes' : IDL.Null,
    'oneHundredTwentyMinutes' : IDL.Null,
    'ninetyMinutes' : IDL.Null,
  });
  const Door = IDL.Record({
    'id' : DoorId,
    'floor' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : Time,
    'building' : IDL.Text,
    'company' : IDL.Text,
    'dimensions' : IDL.Text,
    'leafConfig' : LeafConfig,
    'doorType' : DoorType,
    'notes' : IDL.Text,
    'doorMaterial' : DoorMaterial,
    'frameMaterial' : FrameMaterial,
    'location' : IDL.Text,
    'fireRating' : FireRating,
  });
  const InspectionId = IDL.Nat;
  const Checklist = IDL.Record({
    'frame' : IDL.Bool,
    'glazing' : IDL.Bool,
    'certificatePlate' : IDL.Bool,
    'doorCloser' : IDL.Bool,
    'threshold' : IDL.Bool,
    'signage' : IDL.Bool,
    'hinges' : IDL.Bool,
    'latch' : IDL.Bool,
    'seals' : IDL.Bool,
    'intumescentStrip' : IDL.Bool,
    'doorLeaf' : IDL.Bool,
    'noObstructions' : IDL.Bool,
    'selfClosing' : IDL.Bool,
    'visionPanel' : IDL.Bool,
  });
  const InspectionStatus = IDL.Variant({
    'fail' : IDL.Null,
    'pass' : IDL.Null,
    'actionRequired' : IDL.Null,
  });
  const Inspection = IDL.Record({
    'id' : InspectionId,
    'inspectionDate' : Time,
    'doorId' : DoorId,
    'inspectorName' : IDL.Text,
    'createdAt' : Time,
    'company' : IDL.Text,
    'notes' : IDL.Text,
    'checklist' : Checklist,
    'overallStatus' : InspectionStatus,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'pending' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'principal' : IDL.Principal,
    'status' : ApprovalStatus,
  });
  const DoorAttachment = IDL.Record({
    'id' : AttachmentId,
    'doorId' : DoorId,
    'filename' : IDL.Text,
    'blobHash' : IDL.Text,
    'uploadedAt' : Time,
  });
  const StripeConfiguration = IDL.Record({
    'secretKey' : IDL.Text,
    'allowedCountries' : IDL.Vec(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'currency' : IDL.Text,
    'productName' : IDL.Text,
    'productDescription' : IDL.Text,
    'priceInCents' : IDL.Nat,
    'quantity' : IDL.Nat,
  });
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDoor' : IDL.Func([Door], [DoorId], []),
    'addInspection' : IDL.Func([Inspection], [InspectionId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'deleteDoor' : IDL.Func([DoorId], [], []),
    'editDoor' : IDL.Func([DoorId, Door], [], []),
    'getAllDoors' : IDL.Func([], [IDL.Vec(Door)], ['query']),
    'getAllInspections' : IDL.Func([], [IDL.Vec(Inspection)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoor' : IDL.Func([DoorId], [Door], ['query']),
    'getDoorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getInspection' : IDL.Func([InspectionId], [Inspection], ['query']),
    'getInspectionsForDoor' : IDL.Func([DoorId], [IDL.Vec(Inspection)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getPublicDoor' : IDL.Func([DoorId], [IDL.Opt(Door)], ['query']),
    'getPublicInspectionsForDoor' : IDL.Func([DoorId], [IDL.Vec(Inspection)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'createCheckoutSession' : IDL.Func([IDL.Vec(ShoppingItem), IDL.Text, IDL.Text], [IDL.Text], []),
    'addDoorAttachment' : IDL.Func([DoorId, IDL.Text, IDL.Text], [AttachmentId], []),
    'getDoorAttachments' : IDL.Func([DoorId], [IDL.Vec(DoorAttachment)], ['query']),
    'removeDoorAttachment' : IDL.Func([DoorId, AttachmentId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
