/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Checklist {
  'frame' : boolean,
  'glazing' : boolean,
  'certificatePlate' : boolean,
  'doorCloser' : boolean,
  'threshold' : boolean,
  'signage' : boolean,
  'hinges' : boolean,
  'latch' : boolean,
  'seals' : boolean,
  'intumescentStrip' : boolean,
  'doorLeaf' : boolean,
  'noObstructions' : boolean,
  'selfClosing' : boolean,
  'visionPanel' : boolean,
}
export interface Door {
  'id' : DoorId,
  'floor' : string,
  'active' : boolean,
  'createdAt' : Time,
  'building' : string,
  'company' : string,
  'dimensions' : string,
  'leafConfig' : LeafConfig,
  'doorType' : DoorType,
  'notes' : string,
  'doorMaterial' : DoorMaterial,
  'frameMaterial' : FrameMaterial,
  'location' : string,
  'fireRating' : FireRating,
}
export type DoorId = bigint;
export type AttachmentId = bigint;
export type DoorMaterial = { 'timber' : null } |
  { 'aluminium' : null } |
  { 'hybrid' : null } |
  { 'steel' : null };
export type DoorType = { 'double' : null } |
  { 'hinged' : null } |
  { 'sliding' : null } |
  { 'single' : null };
export type FireRating = { 'sixtyMinutes' : null } |
  { 'thirtyMinutes' : null } |
  { 'oneHundredTwentyMinutes' : null } |
  { 'ninetyMinutes' : null };
export type FrameMaterial = { 'metal' : null } |
  { 'timber' : null } |
  { 'uPVC' : null } |
  { 'hybrid' : null };
export interface Inspection {
  'id' : InspectionId,
  'inspectionDate' : Time,
  'doorId' : DoorId,
  'inspectorName' : string,
  'createdAt' : Time,
  'company' : string,
  'notes' : string,
  'checklist' : Checklist,
  'overallStatus' : InspectionStatus,
}
export type InspectionId = bigint;
export type InspectionStatus = { 'fail' : null } |
  { 'pass' : null } |
  { 'actionRequired' : null };
export type LeafConfig = { 'doubleLeaf' : null } |
  { 'astragalBar' : null } |
  { 'singleLeaf' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type ApprovalStatus = { 'approved' : null } |
  { 'rejected' : null } |
  { 'pending' : null };
export interface UserApprovalInfo {
  'principal' : Principal,
  'status' : ApprovalStatus,
}
export interface DoorAttachment {
  'id' : AttachmentId,
  'doorId' : DoorId,
  'filename' : string,
  'blobHash' : string,
  'uploadedAt' : Time,
}
export interface StripeConfiguration {
  'secretKey' : string,
  'allowedCountries' : Array<string>,
}
export interface ShoppingItem {
  'currency' : string,
  'productName' : string,
  'productDescription' : string,
  'priceInCents' : bigint,
  'quantity' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDoor' : ActorMethod<[Door], DoorId>,
  'addInspection' : ActorMethod<[Inspection], InspectionId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], boolean>,
  'deleteDoor' : ActorMethod<[DoorId], undefined>,
  'editDoor' : ActorMethod<[DoorId, Door], undefined>,
  'getAllDoors' : ActorMethod<[], Array<Door>>,
  'getAllInspections' : ActorMethod<[], Array<Inspection>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoor' : ActorMethod<[DoorId], Door>,
  'getDoorCount' : ActorMethod<[], bigint>,
  'getInspection' : ActorMethod<[InspectionId], Inspection>,
  'getInspectionsForDoor' : ActorMethod<[DoorId], Array<Inspection>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getPublicDoor' : ActorMethod<[DoorId], [] | [Door]>,
  'getPublicInspectionsForDoor' : ActorMethod<[DoorId], Array<Inspection>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'createCheckoutSession' : ActorMethod<[Array<ShoppingItem>, string, string], string>,
  'addDoorAttachment' : ActorMethod<[DoorId, string, string], AttachmentId>,
  'getDoorAttachments' : ActorMethod<[DoorId], Array<DoorAttachment>>,
  'removeDoorAttachment' : ActorMethod<[DoorId, AttachmentId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
