/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Inspection {
    id: InspectionId;
    inspectionDate: Time;
    doorId: DoorId;
    inspectorName: string;
    createdAt: Time;
    company: string;
    notes: string;
    checklist: Checklist;
    overallStatus: InspectionStatus;
}
export type DoorId = bigint;
export interface Door {
    id: DoorId;
    floor: string;
    active: boolean;
    createdAt: Time;
    building: string;
    company: string;
    leafConfig: LeafConfig;
    doorType: DoorType;
    notes: string;
    doorMaterial: DoorMaterial;
    frameMaterial: FrameMaterial;
    location: string;
    fireRating: FireRating;
}
export type InspectionId = bigint;
export interface Checklist {
    frame: boolean;
    glazing: boolean;
    certificatePlate: boolean;
    doorCloser: boolean;
    threshold: boolean;
    signage: boolean;
    hinges: boolean;
    latch: boolean;
    seals: boolean;
    intumescentStrip: boolean;
    doorLeaf: boolean;
    noObstructions: boolean;
    selfClosing: boolean;
    visionPanel: boolean;
}
export interface UserProfile {
    name: string;
}
export enum DoorMaterial {
    timber = "timber",
    aluminium = "aluminium",
    hybrid = "hybrid",
    steel = "steel"
}
export enum DoorType {
    double_ = "double",
    hinged = "hinged",
    sliding = "sliding",
    single = "single"
}
export enum FireRating {
    sixtyMinutes = "sixtyMinutes",
    thirtyMinutes = "thirtyMinutes",
    oneHundredTwentyMinutes = "oneHundredTwentyMinutes",
    ninetyMinutes = "ninetyMinutes"
}
export enum FrameMaterial {
    metal = "metal",
    timber = "timber",
    uPVC = "uPVC",
    hybrid = "hybrid"
}
export enum InspectionStatus {
    fail = "fail",
    pass = "pass",
    actionRequired = "actionRequired"
}
export enum LeafConfig {
    doubleLeaf = "doubleLeaf",
    astragalBar = "astragalBar",
    singleLeaf = "singleLeaf"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDoor(door: Door): Promise<DoorId>;
    addInspection(inspection: Inspection): Promise<InspectionId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDoor(doorId: DoorId): Promise<void>;
    editDoor(doorId: DoorId, door: Door): Promise<void>;
    getAllDoors(): Promise<Array<Door>>;
    getAllInspections(): Promise<Array<Inspection>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoor(doorId: DoorId): Promise<Door>;
    getDoorCount(): Promise<bigint>;
    getInspection(inspectionId: InspectionId): Promise<Inspection>;
    getInspectionsForDoor(doorId: DoorId): Promise<Array<Inspection>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Checklist as _Checklist, Door as _Door, DoorId as _DoorId, DoorMaterial as _DoorMaterial, DoorType as _DoorType, FireRating as _FireRating, FrameMaterial as _FrameMaterial, Inspection as _Inspection, InspectionId as _InspectionId, InspectionStatus as _InspectionStatus, LeafConfig as _LeafConfig, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDoor(arg0: Door): Promise<DoorId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoor(to_candid_Door_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoor(to_candid_Door_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInspection(arg0: Inspection): Promise<InspectionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addInspection(to_candid_Inspection_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInspection(to_candid_Inspection_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDoor(arg0: DoorId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoor(arg0);
            return result;
        }
    }
    async editDoor(arg0: DoorId, arg1: Door): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editDoor(arg0, to_candid_Door_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editDoor(arg0, to_candid_Door_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllDoors(): Promise<Array<Door>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoors();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoors();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInspections(): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInspections();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInspections();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoor(arg0: DoorId): Promise<Door> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoor(arg0);
                return from_candid_Door_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoor(arg0);
            return from_candid_Door_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoorCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoorCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoorCount();
            return result;
        }
    }
    async getInspection(arg0: InspectionId): Promise<Inspection> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspection(arg0);
                return from_candid_Inspection_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspection(arg0);
            return from_candid_Inspection_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInspectionsForDoor(arg0: DoorId): Promise<Array<Inspection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInspectionsForDoor(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInspectionsForDoor(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_DoorMaterial_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoorMaterial): DoorMaterial {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_DoorType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoorType): DoorType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Door_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Door): Door {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_FireRating_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FireRating): FireRating {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_FrameMaterial_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FrameMaterial): FrameMaterial {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_InspectionStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InspectionStatus): InspectionStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Inspection_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inspection): Inspection {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_LeafConfig_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeafConfig): LeafConfig {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DoorId;
    floor: string;
    active: boolean;
    createdAt: _Time;
    building: string;
    company: string;
    leafConfig: _LeafConfig;
    doorType: _DoorType;
    notes: string;
    doorMaterial: _DoorMaterial;
    frameMaterial: _FrameMaterial;
    location: string;
    fireRating: _FireRating;
}): {
    id: DoorId;
    floor: string;
    active: boolean;
    createdAt: Time;
    building: string;
    company: string;
    leafConfig: LeafConfig;
    doorType: DoorType;
    notes: string;
    doorMaterial: DoorMaterial;
    frameMaterial: FrameMaterial;
    location: string;
    fireRating: FireRating;
} {
    return {
        id: value.id,
        floor: value.floor,
        active: value.active,
        createdAt: value.createdAt,
        building: value.building,
        company: value.company,
        leafConfig: from_candid_LeafConfig_n22(_uploadFile, _downloadFile, value.leafConfig),
        doorType: from_candid_DoorType_n24(_uploadFile, _downloadFile, value.doorType),
        notes: value.notes,
        doorMaterial: from_candid_DoorMaterial_n26(_uploadFile, _downloadFile, value.doorMaterial),
        frameMaterial: from_candid_FrameMaterial_n28(_uploadFile, _downloadFile, value.frameMaterial),
        location: value.location,
        fireRating: from_candid_FireRating_n30(_uploadFile, _downloadFile, value.fireRating)
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InspectionId;
    inspectionDate: _Time;
    doorId: _DoorId;
    inspectorName: string;
    createdAt: _Time;
    company: string;
    notes: string;
    checklist: _Checklist;
    overallStatus: _InspectionStatus;
}): {
    id: InspectionId;
    inspectionDate: Time;
    doorId: DoorId;
    inspectorName: string;
    createdAt: Time;
    company: string;
    notes: string;
    checklist: Checklist;
    overallStatus: InspectionStatus;
} {
    return {
        id: value.id,
        inspectionDate: value.inspectionDate,
        doorId: value.doorId,
        inspectorName: value.inspectorName,
        createdAt: value.createdAt,
        company: value.company,
        notes: value.notes,
        checklist: value.checklist,
        overallStatus: from_candid_InspectionStatus_n35(_uploadFile, _downloadFile, value.overallStatus)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doubleLeaf: null;
} | {
    astragalBar: null;
} | {
    singleLeaf: null;
}): LeafConfig {
    return "doubleLeaf" in value ? LeafConfig.doubleLeaf : "astragalBar" in value ? LeafConfig.astragalBar : "singleLeaf" in value ? LeafConfig.singleLeaf : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    double: null;
} | {
    hinged: null;
} | {
    sliding: null;
} | {
    single: null;
}): DoorType {
    return "double" in value ? DoorType.double : "hinged" in value ? DoorType.hinged : "sliding" in value ? DoorType.sliding : "single" in value ? DoorType.single : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timber: null;
} | {
    aluminium: null;
} | {
    hybrid: null;
} | {
    steel: null;
}): DoorMaterial {
    return "timber" in value ? DoorMaterial.timber : "aluminium" in value ? DoorMaterial.aluminium : "hybrid" in value ? DoorMaterial.hybrid : "steel" in value ? DoorMaterial.steel : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metal: null;
} | {
    timber: null;
} | {
    uPVC: null;
} | {
    hybrid: null;
}): FrameMaterial {
    return "metal" in value ? FrameMaterial.metal : "timber" in value ? FrameMaterial.timber : "uPVC" in value ? FrameMaterial.uPVC : "hybrid" in value ? FrameMaterial.hybrid : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sixtyMinutes: null;
} | {
    thirtyMinutes: null;
} | {
    oneHundredTwentyMinutes: null;
} | {
    ninetyMinutes: null;
}): FireRating {
    return "sixtyMinutes" in value ? FireRating.sixtyMinutes : "thirtyMinutes" in value ? FireRating.thirtyMinutes : "oneHundredTwentyMinutes" in value ? FireRating.oneHundredTwentyMinutes : "ninetyMinutes" in value ? FireRating.ninetyMinutes : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fail: null;
} | {
    pass: null;
} | {
    actionRequired: null;
}): InspectionStatus {
    return "fail" in value ? InspectionStatus.fail : "pass" in value ? InspectionStatus.pass : "actionRequired" in value ? InspectionStatus.actionRequired : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Door>): Array<Door> {
    return value.map((x)=>from_candid_Door_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inspection>): Array<Inspection> {
    return value.map((x)=>from_candid_Inspection_n33(_uploadFile, _downloadFile, x));
}
function to_candid_DoorMaterial_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoorMaterial): _DoorMaterial {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_DoorType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoorType): _DoorType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Door_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Door): _Door {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FireRating_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FireRating): _FireRating {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_FrameMaterial_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FrameMaterial): _FrameMaterial {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_InspectionStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionStatus): _InspectionStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Inspection_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Inspection): _Inspection {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_LeafConfig_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeafConfig): _LeafConfig {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: InspectionId;
    inspectionDate: Time;
    doorId: DoorId;
    inspectorName: string;
    createdAt: Time;
    company: string;
    notes: string;
    checklist: Checklist;
    overallStatus: InspectionStatus;
}): {
    id: _InspectionId;
    inspectionDate: _Time;
    doorId: _DoorId;
    inspectorName: string;
    createdAt: _Time;
    company: string;
    notes: string;
    checklist: _Checklist;
    overallStatus: _InspectionStatus;
} {
    return {
        id: value.id,
        inspectionDate: value.inspectionDate,
        doorId: value.doorId,
        inspectorName: value.inspectorName,
        createdAt: value.createdAt,
        company: value.company,
        notes: value.notes,
        checklist: value.checklist,
        overallStatus: to_candid_InspectionStatus_n15(_uploadFile, _downloadFile, value.overallStatus)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: DoorId;
    floor: string;
    active: boolean;
    createdAt: Time;
    building: string;
    company: string;
    leafConfig: LeafConfig;
    doorType: DoorType;
    notes: string;
    doorMaterial: DoorMaterial;
    frameMaterial: FrameMaterial;
    location: string;
    fireRating: FireRating;
}): {
    id: _DoorId;
    floor: string;
    active: boolean;
    createdAt: _Time;
    building: string;
    company: string;
    leafConfig: _LeafConfig;
    doorType: _DoorType;
    notes: string;
    doorMaterial: _DoorMaterial;
    frameMaterial: _FrameMaterial;
    location: string;
    fireRating: _FireRating;
} {
    return {
        id: value.id,
        floor: value.floor,
        active: value.active,
        createdAt: value.createdAt,
        building: value.building,
        company: value.company,
        leafConfig: to_candid_LeafConfig_n3(_uploadFile, _downloadFile, value.leafConfig),
        doorType: to_candid_DoorType_n5(_uploadFile, _downloadFile, value.doorType),
        notes: value.notes,
        doorMaterial: to_candid_DoorMaterial_n7(_uploadFile, _downloadFile, value.doorMaterial),
        frameMaterial: to_candid_FrameMaterial_n9(_uploadFile, _downloadFile, value.frameMaterial),
        location: value.location,
        fireRating: to_candid_FireRating_n11(_uploadFile, _downloadFile, value.fireRating)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FrameMaterial): {
    metal: null;
} | {
    timber: null;
} | {
    uPVC: null;
} | {
    hybrid: null;
} {
    return value == FrameMaterial.metal ? {
        metal: null
    } : value == FrameMaterial.timber ? {
        timber: null
    } : value == FrameMaterial.uPVC ? {
        uPVC: null
    } : value == FrameMaterial.hybrid ? {
        hybrid: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FireRating): {
    sixtyMinutes: null;
} | {
    thirtyMinutes: null;
} | {
    oneHundredTwentyMinutes: null;
} | {
    ninetyMinutes: null;
} {
    return value == FireRating.sixtyMinutes ? {
        sixtyMinutes: null
    } : value == FireRating.thirtyMinutes ? {
        thirtyMinutes: null
    } : value == FireRating.oneHundredTwentyMinutes ? {
        oneHundredTwentyMinutes: null
    } : value == FireRating.ninetyMinutes ? {
        ninetyMinutes: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InspectionStatus): {
    fail: null;
} | {
    pass: null;
} | {
    actionRequired: null;
} {
    return value == InspectionStatus.fail ? {
        fail: null
    } : value == InspectionStatus.pass ? {
        pass: null
    } : value == InspectionStatus.actionRequired ? {
        actionRequired: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeafConfig): {
    doubleLeaf: null;
} | {
    astragalBar: null;
} | {
    singleLeaf: null;
} {
    return value == LeafConfig.doubleLeaf ? {
        doubleLeaf: null
    } : value == LeafConfig.astragalBar ? {
        astragalBar: null
    } : value == LeafConfig.singleLeaf ? {
        singleLeaf: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoorType): {
    double: null;
} | {
    hinged: null;
} | {
    sliding: null;
} | {
    single: null;
} {
    return value == DoorType.double ? {
        double_: null
    } : value == DoorType.hinged ? {
        hinged: null
    } : value == DoorType.sliding ? {
        sliding: null
    } : value == DoorType.single ? {
        single: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DoorMaterial): {
    timber: null;
} | {
    aluminium: null;
} | {
    hybrid: null;
} | {
    steel: null;
} {
    return value == DoorMaterial.timber ? {
        timber: null
    } : value == DoorMaterial.aluminium ? {
        aluminium: null
    } : value == DoorMaterial.hybrid ? {
        hybrid: null
    } : value == DoorMaterial.steel ? {
        steel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
